# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ns_connector"
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christian Marie <pingu@anchor.com.au>"]
  s.date = "2013-06-17"
  s.description = "This library provides an interface to NetSuite via'RESTlets'. This appears to be a quicker and more reliableway of interfacing with NetSuite records than the SOAP API."
  s.email = "pingu@anchor.com.au"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "HACKING",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/ns_connector.rb",
    "lib/ns_connector/attaching.rb",
    "lib/ns_connector/chunked_searching.rb",
    "lib/ns_connector/config.rb",
    "lib/ns_connector/errors.rb",
    "lib/ns_connector/field_store.rb",
    "lib/ns_connector/hash.rb",
    "lib/ns_connector/resource.rb",
    "lib/ns_connector/resources.rb",
    "lib/ns_connector/resources/contact.rb",
    "lib/ns_connector/resources/customer.rb",
    "lib/ns_connector/resources/invoice.rb",
    "lib/ns_connector/restlet.rb",
    "lib/ns_connector/sublist.rb",
    "lib/ns_connector/sublist_item.rb",
    "misc/failed_sublist_saving_patch",
    "scripts/run_restlet",
    "scripts/test_shell",
    "spec/attaching_spec.rb",
    "spec/chunked_searching_spec.rb",
    "spec/config_spec.rb",
    "spec/resource_spec.rb",
    "spec/resources/contact_spec.rb",
    "spec/resources/customer_spec.rb",
    "spec/resources/invoice_spec.rb",
    "spec/restlet_spec.rb",
    "spec/spec_helper.rb",
    "spec/sublist_item_spec.rb",
    "spec/sublist_spec.rb",
    "spec/support/mock_data.rb",
    "support/read_only_test",
    "support/restlet.js",
    "support/super_dangerous_write_test"
  ]
  s.homepage = "https://github.com/christian-marie/ns_connector"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "An interface to NetSuite records via RESTlets."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<webmock>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<pry-debugger>, [">= 0"])
      s.add_development_dependency(%q<guard-rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<webmock>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<pry-debugger>, [">= 0"])
      s.add_dependency(%q<guard-rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<webmock>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<pry-debugger>, [">= 0"])
    s.add_dependency(%q<guard-rspec>, [">= 0"])
  end
end

